[Feat] IEEE Xplore 값
vislab-ssu/vis-paperlist-BE pull request #5
Opened 2024-02-09 08:39 UTC by candosh

## IEEE Xplore api 연동 값

## 이슈 번호
- #3 

## 논의 사항
- Session 값이 따로 없어  "Content Type": "Conferences" 으로 가져왔습니다. 필요 없는 경우 제거 하겠습니다.
-  date값이 지금 형식은 "date": "19-21 April 2010"인데, 일까지 넣어도 괜찮은지

### 수정 필요한 부분 수정후 assets -> new에 데이터 추가해두겠습니다

2024-02-09 23:35 UTC, mathpaul3 requested changes

2024-02-10 10:04 UTC, candosh commented on crawling/OpenCitation/OC_api.py
> +HTTP_HEADERS = {"Authorization": "089eb33b-2ab6-4679-9425-9ab03157d3e0"}
넵! 나중에 빼고 올리려고 했는데, 까먹었네요!😅 감사합니다!! 🙏🏻

2024-02-10 10:06 UTC, candosh commented on crawling/IEEE-Explore/IEEEVIS_api.py
넵 감사합니다! :)

2024-02-11 05:38 UTC, candosh commented
코드 리뷰 반영 완료했고, 머지 하겠습니다!

2024-02-11 05:39 UTC, merged